LOG_LEVEL: "info"
HTTP_SERVER_PORT: "1111"

DATABASE_HOST: "127.0.0.1"
DATABASE_PORT: 3306
DATABASE_USERNAME: "root"
DATABASE_PASSWORD: "dbpassword"
DATABASE_DBNAME: "lucky"
DATABASE_MAX_OPEN_CONNECTION: ""
DATABASE_MAX_IDLE_CONNECTION: ""
DATABASE_CONNECTION_MAX_IDLE_TIME_IN_SECOND: ""
DATABASE_CONNECTION_MAX_LIFE_TIME_IN_SECOND: ""

HTTP_GRACEFUL_SHUTDOWN_TIMEOUT: "10s"

# end of env